[bumpver]
current_version = "v2.3.5"
version_pattern = "vMAJOR.MINOR.PATCH"
commit_message = "bump version {old_version} -> {new_version}"
tag_message = "{new_version}"
tag_scope = "default"
pre_commit_hook = ""
post_commit_hook = ""
commit = true
tag = true
push = true

[bumpver.file_patterns]
"package.json" = ['"version": "{pep440_version}"']
"bumpver.toml" = ['current_version = "{version}"']
