name: bump-version-test

on:
  push:

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.RELEASE_SSH_KEY }}
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          cache: "yarn"
          node-version-file: ".tool-versions"
      - name: Setup build dependencies
        run: |
          make deps
          yarn install
      - name: Configure Git user
        run: |
          git config user.name "jocmp"
          git config user.email "9521010+jocmp@users.noreply.github.com"
      - name: Bump Version
        run: |
          BUMPVER_NEW_VERSION=v2.2.7 make changelog
